apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-frontend
  template:
    metadata:
      labels:
        app: hms-frontend
    spec:
      containers:
        - name: hms-frontend
          image: gnaneswar4/hms-frontend:v1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hms-frontend-service
spec:
  type: NodePort
  selector:
    app: hms-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080